name: platform_device_id_platform_interface
description: A common platform interface for the platform_device_id plugin.
homepage: https://github.com/BestBurning/platform_device_id/tree/master/platform_device_id_platform_interface
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: ">=3.0.3"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

