name: platform_device_id_macos
description: macOS implementation of the platform_device_id plugin.
version: 1.0.0
homepage: https://github.com/BestBurning/platform_device_id/tree/master/platform_device_id_macos

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: platform_device_id
    platforms:
      macos:
        pluginClass: PlatformDeviceIdMacosPlugin
        fileName: platform_device_id_macos.dart
