name: platform_device_id_web
description: web implementation of the platform_device_id plugin.
version: 1.0.0
homepage: https://github.com/BestBurning/platform_device_id/tree/master/platform_device_id_linux

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  platform_device_id_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: platform_device_id
    platforms:
      web:
        pluginClass: PlatformDeviceIdWebPlugin
        fileName: platform_device_id_web.dart
